public class SuperMan extends Person implements Flyer{
    
    // this class have to implement all the functions definded in the Flyer Interface
   
    // properties of person + extra features of SuperMan
    // interface only have function definition not implementsion
    
    public void takeoff(){
        // super man will takeoff for fly
    }
    public void fly(){
       // superman will fly    
    }
    public void land(){
        
        // superman will land after fly
    }
    
}